# Generated by Django 5.2.4 on 2025-08-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('context', models.TextField(blank=True, null=True)),
                ('screenshot', models.TextField(blank=True, null=True)),
                ('ocr', models.TextField(blank=True, null=True)),
                ('question1', models.TextField(blank=True, null=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('question2', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('gpt_result', models.TextField(blank=True, null=True)),
                ('gpt_result_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'redflagcheck_analyses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_balance', models.IntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('magic_code', models.CharField(blank=True, max_length=255, null=True)),
                ('magic_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'redflagcheck_users',
                'managed': False,
            },
        ),
    ]
