# Generated by Django 5.2.5 on 2025-09-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redflagcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='followup_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysis',
            name='followup_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='ocr_corrected_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='ocr_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('intake', 'Intake verzameld'), ('followup_pending', 'Follow-up gevraagd'), ('ready', 'Klaar voor analyse')], db_index=True, default='intake', max_length=32),
        ),
    ]
