# Generated by Django 5.2.5 on 2025-09-18 18:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redflagcheck', '0002_analysis_followup_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wp_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=16)),
                ('subject_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Volgorde binnen de analyse (1,2,...)')),
                ('question_text', models.TextField()),
                ('why', models.TextField()),
                ('answer_text', models.TextField(help_text='Antwoord van de gebruiker (verplicht).')),
                ('model_version', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['analysis', 'position', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='data',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='followup_answers',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='followup_questions',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='ocr_corrected_text',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='wp_user',
        ),
        migrations.AddField(
            model_name='analysis',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysis',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='input_text',
            field=models.TextField(default='', help_text='Originele tekst van gebruiker (verplicht).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='mood_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Verwijzing naar de eerste/bovenliggende analyse.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='redflagcheck.analysis'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='result_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='result_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='result_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='round',
            field=models.PositiveIntegerField(default=1, help_text='Ronde in casus (≥1).', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='screenshot_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='wp_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('intake', 'Intake opgeslagen'), ('questions_ready', 'Vragen gegenereerd'), ('answers_saved', 'Antwoorden opgeslagen'), ('completed', 'Afronding gereed')], db_index=True, default='intake', max_length=32),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['created_at'], name='redflagchec_created_cc7fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['updated_at'], name='redflagchec_updated_160864_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status'], name='redflagchec_status_644eca_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['ip_address'], name='redflagchec_ip_addr_a2a95a_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['deleted_at'], name='redflagchec_deleted_5c23e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.UniqueConstraint(fields=('parent', 'round'), name='uniq_round_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(('round__gte', 1)), name='ck_round_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='ck_rating_1_5_or_null'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mood_score__gte', 1), ('mood_score__lte', 5)), ('mood_score__isnull', True), _connector='OR'), name='ck_mood_1_5_or_null'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['type', 'severity'], name='redflagchec_type_703700_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['wp_user_id', 'created_at'], name='redflagchec_wp_user_345f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['subject_ref'], name='redflagchec_subject_3ad41f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address'], name='redflagchec_ip_addr_622c87_idx'),
        ),
        migrations.AddField(
            model_name='followup',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='redflagcheck.analysis'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['created_at'], name='redflagchec_created_3b3407_idx'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(fields=('analysis', 'position'), name='uniq_followup_position_per_analysis'),
        ),
    ]
