# Generated by Django 5.2.5 on 2025-09-18 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redflagcheck', '0003_auditevent_followup_alter_analysis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.RemoveIndex(
            model_name='analysis',
            name='redflagchec_created_cc7fb8_idx',
        ),
        migrations.RemoveIndex(
            model_name='analysis',
            name='redflagchec_updated_160864_idx',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
